feat: lib app creation
Darkmixt12/VyM pull request #1
Opened 2023-11-15 21:48 UTC by Darkmixt12

Odio a claudio

2023-11-15 21:54 UTC, cvandradg requested changes
check the mentioned comment

2023-11-15 21:54 UTC, cvandradg commented on libs/vym/frontend/ui/app/src/lib/components/app.component.html
> +<vym-footer></vym-footer>
you missing a space here, make sure to check lint or npx nx format

2023-11-15 21:55 UTC, cvandradg commented
Also, I don't see evidences that the tests are running fine

2023-11-15 23:00 UTC, Darkmixt12 commented
![Screenshot_1](https://github.com/Darkmixt12/VyM/assets/137929047/22e8c962-ec38-4db4-b12f-0c1f53a3f348)

2023-11-16 02:11 UTC, cvandradg approved these changes
LGTM

2023-11-16 14:06 UTC, merged